### ISSUE TITLE
Stack does not deploy due to ubuntu not having due to no aws-cfn-bootstrap being installed or available

### ISSUE THREAD

**Issue by jeff2work** [aws-samples/amazon-chime-sdk-call-analytics-recorder#46]
Since aws-cfn-bootstrap is not installed, fails to get signal and rolls back

**Comment by schuettc** [comment]
Just deployed without issue.  Can you try again?  Or was there an error in the `/var/log/cloud-init-output.log`?

 ✅  amazon-chime-sdk-call-analytics-recording

✨  Deployment time: 463.74s

Outputs:
Stack ARN:
arn:aws:cloudformation:us-east-1:104621577074:stack/amazon-chime-sdk-call-analytics-recording/f872d110-b03a-11ee-9af9-0e4c8a6d5a9b

**Comment by jeff2work** [comment]
The aws-cfn-bootstrap is not installed, so no cfn-signal or cfn-init comands complete.

![image](https://github.com/aws-samples/amazon-chime-sdk-call-analytics-recorder/assets/78390272/b36db21b-46e6-4843-b180-e8a6004e510e)


[cloud-init.log](https://github.com/aws-samples/amazon-chime-sdk-call-analytics-recorder/files/13907097/cloud-init.log)

**Comment by jeff2work** [comment]
I see none of the userdata commands being run. I tried running the commands on the instance, but it appears the install of the aws-cfn-bootstrap was installed in the wrong place. Then I am having issues running this command cfn-signal -e $? --region. We have tried this deployment over 15 times with the same result?

**Comment by jeff2work** [comment]
Also, one command causes a 60 second delay: 

![image](https://github.com/aws-samples/amazon-chime-sdk-call-analytics-recorder/assets/78390272/d535db57-a64c-45ae-8eb3-890655c232c4)

**Comment by jeff2work** [comment]
I was able to run all the commands except for these  two return failure even though the instance was running: 

/opt/aws/bin/cfn-init -v --region us-east-1 --stack amazon-chime-sdk-call-analytics-recorder --resource <instance> --url https://cloudformation.us-east-1.amazonaws.com --role <role> -c default

/opt/aws/bin/cfn-signal -e $? --region us-east-1 --stack amazon-chime-sdk-call-analytics-recorder --resource <instance> --url https://cloudformation.us-east-1.amazonaws.com --role <role>

**Comment by schuettc** [comment]
Yeah, there are a few things that need cleaned up in there.  I'll take a look and see about updating.

**Comment by jeff2work** [comment]
Any way you may be able to help with the syntax of the above commands? I was able to get everything else installed, just the last 2 commands to signal success, is what I need to complete it, I believe.

**Comment by schuettc** [comment]
Updated the server code.  Can you try deploying again?

```bash
2024-01-12 04:43:48,238 [DEBUG] No services specified
2024-01-12 04:43:48,241 [INFO] ConfigSets completed
2024-01-12 04:43:48,241 [DEBUG] Not clearing reboot trigger as scheduling support is not available
2024-01-12 04:43:48,241 [INFO] -----------------------Build complete-----------------------
2024-01-12 04:43:48,707 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-1.amazonaws.com
2024-01-12 04:43:48,707 [DEBUG] Signaling resource ServerResourcesInstance6D1E6643e513b67a7697beb0 in stack amazon-chime-sdk-call-analytics-recording with unique ID i-0973d20d2902db117 and status SUCCESS
```

https://github.com/aws-samples/amazon-chime-sdk-call-analytics-recorder/commit/2c6af473a4ed6ead77f957dce628db11d46f7a59

**Comment by jeff2work** [comment]
I cloned the repository again, but I can't even get yarn launch to start a stack at this point? I'll look at it tomorrow.

Bundling asset amazon-chime-sdk-call-analytics-recording/LambdaResources/sageMakerCustomResourceLambda/Code/Stage...
warning package.json: License should be a valid SPDX license expression
$ /home/jeff/amazon-chime-sdk-call-analytics-recorder/node_modules/.bin/esbuild --bundle /home/jeff/amazon-chime-sdk-call-analytics-recorder/src/resources/sageMakerCustomResource/index.ts --target=node18 --platform=node --outfile=/home/jeff/amazon-chime-sdk-call-analytics-recorder/cdk.out/bundling-temp-fa7d99a7b8b4006d7e2ab74e6c13b40236779dd873778287537cd280de51d97e/index.js '--external:@aws-sdk/*'

  cdk.out/bundling-temp-fa7d99a7b8b4006d7e2ab74e6c13b40236779dd873778287537cd280de51d97e/index.js  5.3kb

Error: ENOENT: no such file or directory, open './src/resources/server/config/amazon-cloudwatch-agent.json'
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at Function.fromFileInline (/home/jeff/amazon-chime-sdk-call-analytics-recorder/node_modules/aws-cdk-lib/aws-ec2/lib/cfn-init-elements.js:1:6034)
    at new ServerResources (/home/jeff/amazon-chime-sdk-call-analytics-recorder/src/server.ts:309:22)
    at new AmazonChimeSDKCallAnalyticsRecording (/home/jeff/amazon-chime-sdk-call-analytics-recorder/src/amazon-chime-sdk-call-analytics-recording.ts:98:5)
    at Object.<anonymous> (/home/jeff/amazon-chime-sdk-call-analytics-recorder/src/amazon-chime-sdk-call-analytics-recording.ts:175:1)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module.m._compile (/home/jeff/amazon-chime-sdk-call-analytics-recorder/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Object.require.extensions.<computed> [as .ts] (/home/jeff/amazon-chime-sdk-call-analytics-recorder/node_modules/ts-node/src/index.ts:1621:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './src/resources/server/config/amazon-cloudwatch-agent.json'
}

Subprocess exited with error 1
👾 Task "build » post-compile » synth:silent" failed when executing "cdk synth -q" (cwd: /home/jeff/amazon-chime-sdk-call-analytics-recorder)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
👾 Task "launch" failed when executing "yarn && yarn projen && yarn build && yarn cdk bootstrap && yarn cdk deploy --require-approval never" (cwd: /home/jeff/amazon-chime-sdk-call-analytics-recorder)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by schuettc** [comment]
That file should be there: https://github.com/aws-samples/amazon-chime-sdk-call-analytics-recorder/blob/main/src/resources/server/config/amazon-cloudwatch-agent.json

**Comment by jeff2work** [comment]
Hi,
We were able to get it deployed. I appreciate the efforts.

**Comment by schuettc** [comment]
Greaet.  Glad to hear.  I'll close this for now.  Have some plans to update the stack to support Bedrock instead of Sagemaker as well.
